// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const booksBuyLinks2 = z.object({
  name: z.string().optional(),
  url: z.string().optional(),
});

/**
 *
 * @typedef  {BooksBuyLinks2} booksBuyLinks2
 * @property {string}
 * @property {string}
 */
export type BooksBuyLinks2 = z.infer<typeof booksBuyLinks2>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const booksBuyLinks2Response = z
  .object({
    name: z.string().optional(),
    url: z.string().optional(),
  })
  .transform((data) => ({
    name: data['name'],
    url: data['url'],
  }));

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const booksBuyLinks2Request = z
  .object({ name: z.string().nullish(), url: z.string().nullish() })
  .transform((data) => ({
    name: data['name'],
    url: data['url'],
  }));
