// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import {
  getListsFormatOkResponseResults,
  getListsFormatOkResponseResultsRequest,
  getListsFormatOkResponseResultsResponse,
} from './get-lists-format-ok-response-results';

/**
 * The shape of the model inside the application code - what the users use
 */
export const getListsFormatOkResponse = z.object({
  status: z.string().optional(),
  copyright: z.string().optional(),
  numResults: z.number().optional(),
  lastModified: z.string().optional(),
  results: z.array(getListsFormatOkResponseResults).optional(),
});

/**
 *
 * @typedef  {GetListsFormatOkResponse} getListsFormatOkResponse
 * @property {string}
 * @property {string}
 * @property {number}
 * @property {string}
 * @property {GetListsFormatOkResponseResults[]}
 */
export type GetListsFormatOkResponse = z.infer<typeof getListsFormatOkResponse>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const getListsFormatOkResponseResponse = z
  .object({
    status: z.string().optional(),
    copyright: z.string().optional(),
    num_results: z.number().optional(),
    last_modified: z.string().optional(),
    results: z.array(getListsFormatOkResponseResultsResponse).optional(),
  })
  .transform((data) => ({
    status: data['status'],
    copyright: data['copyright'],
    numResults: data['num_results'],
    lastModified: data['last_modified'],
    results: data['results'],
  }));

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const getListsFormatOkResponseRequest = z
  .object({
    status: z.string().nullish(),
    copyright: z.string().nullish(),
    numResults: z.number().nullish(),
    lastModified: z.string().nullish(),
    results: z.array(getListsFormatOkResponseResultsRequest).nullish(),
  })
  .transform((data) => ({
    status: data['status'],
    copyright: data['copyright'],
    num_results: data['numResults'],
    last_modified: data['lastModified'],
    results: data['results'],
  }));
