// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import { BaseService } from '../base-service';
import { ContentType, HttpResponse } from '../../http';
import { RequestConfig } from '../../http/types';
import {
  GetListsBestSellersHistoryJsonOkResponse,
  GetListsDateListJsonOkResponse,
  GetListsNamesFormatOkResponse,
  getListsBestSellersHistoryJsonOkResponseResponse,
  getListsDateListJsonOkResponseResponse,
  getListsNamesFormatOkResponseResponse,
} from './models';
import {
  GetListsBestSellersHistoryJsonParams,
  GetListsDateListJsonParams,
  GetListsFullOverviewFormatParams,
  GetListsOverviewFormatParams,
} from './request-params';
import { OverviewResponse, overviewResponseResponse } from '../common';

export class ListsService extends BaseService {
  /**
 * Get Best Sellers list by date.
 * @param {string} date - YYYY-MM-DD or "current"

The date the best sellers list was published on NYTimes.com.  Use "current" to get latest list.
 * @param {string} list - Name of the Best Sellers List (e.g. hardcover-fiction). You can get the full list of names from the /lists/names.json service.
 * @param {number} [offset] - Sets the starting point of the result set (0, 20, ...).  Used to paginate thru books if list has more than 20. Defaults to 0.  The num_results field indicates how many books are in the list.
 * @returns {Promise<HttpResponse<GetListsDateListJsonOkResponse>>} Best Sellers list books.
 */
  async getListsDateListJson(
    date: string,
    list: string,
    params?: GetListsDateListJsonParams,
    requestConfig?: RequestConfig,
  ): Promise<HttpResponse<GetListsDateListJsonOkResponse>> {
    const path = this.client.buildPath('/lists/{date}/{list}.json', { date: date, list: list });
    const options: any = {
      responseSchema: getListsDateListJsonOkResponseResponse,
      requestSchema: z.any(),
      queryParams: {},
      headers: {},
      requestContentType: ContentType.Json,
      responseContentType: ContentType.Json,
      retry: requestConfig?.retry,
      config: this.config,
    };
    if (params?.offset) {
      options.queryParams['offset'] = params?.offset;
    }
    return this.client.get(path, options);
  }

  /**
 * Get all books for all the Best Sellers lists for specified date.
 * @param {string} [publishedDate] - YYYY-MM-DD

The best-seller list publication date.
You do not have to specify the exact date the list was published. The service will search forward (into the future) for the closest publication date to the date you specify. For example, a request for lists/overview/2013-05-22 will retrieve the list that was published on 05-26.

If you do not include a published date, the current week's best sellers lists will be returned.
 * @returns {Promise<HttpResponse<OverviewResponse>>} Full overview of Best Sellers lists.
 */
  async getListsFullOverviewFormat(
    params?: GetListsFullOverviewFormatParams,
    requestConfig?: RequestConfig,
  ): Promise<HttpResponse<OverviewResponse>> {
    const path = '/lists/full-overview.json';
    const options: any = {
      responseSchema: overviewResponseResponse,
      requestSchema: z.any(),
      queryParams: {},
      headers: {},
      requestContentType: ContentType.Json,
      responseContentType: ContentType.Json,
      retry: requestConfig?.retry,
      config: this.config,
    };
    if (params?.publishedDate) {
      options.queryParams['published_date'] = params?.publishedDate;
    }
    return this.client.get(path, options);
  }

  /**
 * Get top 5 books for all the Best Sellers lists for specified date.
 * @param {string} [publishedDate] - YYYY-MM-DD

The best-seller list publication date.
You do not have to specify the exact date the list was published. The service will search forward (into the future) for the closest publication date to the date you specify. For example, a request for lists/overview/2013-05-22 will retrieve the list that was published on 05-26.

If you do not include a published date, the current week's best sellers lists will be returned.
 * @returns {Promise<HttpResponse<OverviewResponse>>} Overview of Best Sellers lists.
 */
  async getListsOverviewFormat(
    params?: GetListsOverviewFormatParams,
    requestConfig?: RequestConfig,
  ): Promise<HttpResponse<OverviewResponse>> {
    const path = '/lists/overview.json';
    const options: any = {
      responseSchema: overviewResponseResponse,
      requestSchema: z.any(),
      queryParams: {},
      headers: {},
      requestContentType: ContentType.Json,
      responseContentType: ContentType.Json,
      retry: requestConfig?.retry,
      config: this.config,
    };
    if (params?.publishedDate) {
      options.queryParams['published_date'] = params?.publishedDate;
    }
    return this.client.get(path, options);
  }

  /**
   * Get Best Sellers list names.
   * @returns {Promise<HttpResponse<GetListsNamesFormatOkResponse>>} Get Best Sellers list names.
   */
  async getListsNamesFormat(requestConfig?: RequestConfig): Promise<HttpResponse<GetListsNamesFormatOkResponse>> {
    const path = '/lists/names.json';
    const options: any = {
      responseSchema: getListsNamesFormatOkResponseResponse,
      requestSchema: z.any(),
      headers: {},
      requestContentType: ContentType.Json,
      responseContentType: ContentType.Json,
      retry: requestConfig?.retry,
      config: this.config,
    };
    return this.client.get(path, options);
  }

  /**
 * Get Best Sellers list history.
 * @param {string} [ageGroup] - The target age group for the best seller.
 * @param {string} [author] - The author of the best seller. The author field does not include additional contributors (see Data Structure for more details about the author and contributor fields).

When searching the author field, you can specify any combination of first, middle and last names.

When sort-by is set to author, the results will be sorted by author's first name.
 * @param {string} [contributor] - The author of the best seller, as well as other contributors such as the illustrator (to search or sort by author name only, use author instead).

When searching, you can specify any combination of first, middle and last names of any of the contributors.

When sort-by is set to contributor, the results will be sorted by the first name of the first contributor listed.
 * @param {string} [isbn] - International Standard Book Number, 10 or 13 digits

A best seller may have both 10-digit and 13-digit ISBNs, and may have multiple ISBNs of each type. To search on multiple ISBNs, separate the ISBNs with semicolons (example: 9780446579933;0061374229).
 * @param {number} [offset] - Sets the starting point of the result set (0, 20, ...).  Used to paginate thru results if there are more than 20. Defaults to 0. The num_results field indicates how many results there are total.
 * @param {string} [price] - The publisher's list price of the best seller, including decimal point.
 * @param {string} [publisher] - The standardized name of the publisher
 * @param {string} [title] - The title of the best seller

When searching, you can specify a portion of a title or a full title.
 * @returns {Promise<HttpResponse<GetListsBestSellersHistoryJsonOkResponse>>} Best Sellers list history
 */
  async getListsBestSellersHistoryJson(
    params?: GetListsBestSellersHistoryJsonParams,
    requestConfig?: RequestConfig,
  ): Promise<HttpResponse<GetListsBestSellersHistoryJsonOkResponse>> {
    const path = '/lists/best-sellers/history.json';
    const options: any = {
      responseSchema: getListsBestSellersHistoryJsonOkResponseResponse,
      requestSchema: z.any(),
      queryParams: {},
      headers: {},
      requestContentType: ContentType.Json,
      responseContentType: ContentType.Json,
      retry: requestConfig?.retry,
      config: this.config,
    };
    if (params?.ageGroup) {
      options.queryParams['age-group'] = params?.ageGroup;
    }
    if (params?.author) {
      options.queryParams['author'] = params?.author;
    }
    if (params?.contributor) {
      options.queryParams['contributor'] = params?.contributor;
    }
    if (params?.isbn) {
      options.queryParams['isbn'] = params?.isbn;
    }
    if (params?.offset) {
      options.queryParams['offset'] = params?.offset;
    }
    if (params?.price) {
      options.queryParams['price'] = params?.price;
    }
    if (params?.publisher) {
      options.queryParams['publisher'] = params?.publisher;
    }
    if (params?.title) {
      options.queryParams['title'] = params?.title;
    }
    return this.client.get(path, options);
  }
}
