// This file was generated by liblab | https://liblab.com/

export interface GetListsDateListJsonParams {
  offset?: number;
}

export interface GetListsFullOverviewFormatParams {
  publishedDate?: string;
}

export interface GetListsOverviewFormatParams {
  publishedDate?: string;
}

export interface GetListsBestSellersHistoryJsonParams {
  ageGroup?: string;
  author?: string;
  contributor?: string;
  isbn?: string;
  offset?: number;
  price?: string;
  publisher?: string;
  title?: string;
}
