// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import {
  getReviewsFormatOkResponseResults,
  getReviewsFormatOkResponseResultsRequest,
  getReviewsFormatOkResponseResultsResponse,
} from './get-reviews-format-ok-response-results';

/**
 * The shape of the model inside the application code - what the users use
 */
export const getReviewsFormatOkResponse = z.object({
  status: z.string().optional(),
  copyright: z.string().optional(),
  numResults: z.number().optional(),
  results: z.array(getReviewsFormatOkResponseResults).optional(),
});

/**
 *
 * @typedef  {GetReviewsFormatOkResponse} getReviewsFormatOkResponse
 * @property {string}
 * @property {string}
 * @property {number}
 * @property {GetReviewsFormatOkResponseResults[]}
 */
export type GetReviewsFormatOkResponse = z.infer<typeof getReviewsFormatOkResponse>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const getReviewsFormatOkResponseResponse = z
  .object({
    status: z.string().optional(),
    copyright: z.string().optional(),
    num_results: z.number().optional(),
    results: z.array(getReviewsFormatOkResponseResultsResponse).optional(),
  })
  .transform((data) => ({
    status: data['status'],
    copyright: data['copyright'],
    numResults: data['num_results'],
    results: data['results'],
  }));

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const getReviewsFormatOkResponseRequest = z
  .object({
    status: z.string().nullish(),
    copyright: z.string().nullish(),
    numResults: z.number().nullish(),
    results: z.array(getReviewsFormatOkResponseResultsRequest).nullish(),
  })
  .transform((data) => ({
    status: data['status'],
    copyright: data['copyright'],
    num_results: data['numResults'],
    results: data['results'],
  }));
