// This file was generated by liblab | https://liblab.com/

import { Environment } from './http/environment';
import { SdkConfig } from './http/types';
import { ListsJsonService } from './services/lists-json';
import { ListsService } from './services/lists';
import { ReviewsJsonService } from './services/reviews-json';

export class NytBooksSdk {
  public readonly listsJson: ListsJsonService;

  public readonly lists: ListsService;

  public readonly reviewsJson: ReviewsJsonService;

  constructor(public config: SdkConfig) {
    const baseUrl = config.environment || config.baseUrl || Environment.DEFAULT;
    this.config = {
      ...config,
      baseUrl,
    };
    this.listsJson = new ListsJsonService(this.config);

    this.lists = new ListsService(this.config);

    this.reviewsJson = new ReviewsJsonService(this.config);
  }

  set baseUrl(baseUrl: string) {
    this.listsJson.baseUrl = baseUrl;
    this.lists.baseUrl = baseUrl;
    this.reviewsJson.baseUrl = baseUrl;
  }

  set environment(environment: Environment) {
    this.listsJson.baseUrl = environment;
    this.lists.baseUrl = environment;
    this.reviewsJson.baseUrl = environment;
  }
}

// c029837e0e474b76bc487506e8799df5e3335891efe4fb02bda7a1441840310c
